sudo: required
services:
  - docker

before_install:
  - docker build -t learningdocker2203/docker-react -f Dockergile.dev .

script:
  -- docker run -e CI=true learningdocker2203/docker-react npm run test -- --coverage
